### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by aaronmck** [drivenbyentropy/rnafold4j#1]
Hi @ drivenbyentropy,

Thanks for the great port of the RNA fold tool! My initial tests have worked out really well, and I'd like to incorporate as a scoring metric into our CRISPR guide selection tool, where users are often concerned about gRNA free energy: https://github.com/mckennalab/FlashFry. 

The ViennaRNA team license theirs under what looks like a MIT/BSD license. I was curious if had a license for your port? (ours is under GPLv3). Happy to cite your work in the tool. Thanks!

**Comment by drivenbyentropy** [comment]
Hi @aaronmck. I am happy to see this work could find another use other than for my own projects. I will add this to the main page, but yes, consider it released under the GPLv3. It is my understanding that the MIT/BSD license of the original work allows for this.

**Comment by aaronmck** [comment]
Awesome, thanks again for the great work here!
